var rawSpeakers = [
  /* {
    "name": "",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  } */
  {
    "name": "Monica Sarbu",
    "github": "monicasarbu",
    "twitter": "monicasarbu",
    "bio": "Monica is leading the Ingest team at Elastic, responsible for the popular open source projects Beats (Filebeat, Metricbeat, Auditbeat, Winlogbeat, Packetbeat, Heartbeat) and Logstash, as well as the solutions built on top of the Beats platform like logging and monitoring and SecOps. She is the co-creator of Beats and the creator of the Packetbeat open source project. She gained extensive experience in the monitoring space by working for many years on a complete monitoring and troubleshooting solution for VoIP networks.",
    "title": "You don’t look like an Engineer",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "3be036b2f55557ceacebf476970662de",
  },
  {
    "name": "Marcus Barczak",
    "github": "ickymettle",
    "twitter": "ickymettle",
    "bio": "",
    "title": "Prometheus for Practitioners: Migrating to Prometheus at Fastly",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Michael Kehoe",
    "github": "michael-kehoe",
    "twitter": "matrixtek",
    "bio": "Michael is a Staff SRE at LinkedIn working on Incident Response, Disaster Recovery, Visibility Engineering & Reliability Principles. He specializes in maintaining large system infrastructure as demonstrated by his work at LinkedIn (applications, automation & infrastructure) and at The University of Queensland (networks). Michael has also spent time building small satellites at NASA and writing thermal environments software at Rio Tinto.",
    "title": "What the NTSB teaches us about incident management & postmortems",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "5fc10918108effbbceea324480314c8a",
  },
  {
    "name": "Nina Mushiana",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "What the NTSB teaches us about incident management & postmortems",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Stephen Boak",
    "github": "sboak",
    "twitter": "sboak",
    "bio": "I'm the Director of Product Design at Datadog. Formerly the Co-founder & CPO at Opsee and an early employee at Boundary and Opsmatic, I've been designing monitoring tools for the last 10 years. What's kept me around is the passion and dedication of the engineers I work with, building tools for each other that push the craft of making software forward.",
    "title": "Rethinking UX for AI-driven Monitoring Tools",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "20be221be9bb28194db393512d90b2db",
  },
  {
    "name": "Radu Gheorghe",
    "github": "radu-gheorghe",
    "twitter": "radu0gheorghe",
    "bio": "Radu Gheorghe is a psychologist working as search consultant, software engineer and trainer at Sematext. Mainly on Elasticsearch, Solr and logging-related projects.",
    "title": "Is observability good for our brain? How about post-mortems?",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "2164d281261ff5f5a239a9ccd5bdcad4",
  },
  {
    "name": "Rafał Kuć",
    "github": "gr0",
    "twitter": "kucrafal",
    "bio": "Software engineer, trainer, consultant and author from time to time - some would say that he is an all in one battle weapon concentrated mostly on Lucene, Solr and Elasticsearch. However he also likes all the other cool stuff that is happening in the IT world. Likes to share his knowledge by giving talks at various meet ups and conferences.",
    "title": "Is observability good for our brain? How about post-mortems?",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "d05d7fbddd69c91eefaad0b9ec624111",
  },
  {
    "name": "Stephen Strowes",
    "github": "sdstrowes",
    "twitter": "sdstrowes",
    "bio": "Stephen is a senior researcher in the R&D team at RIPE NCC; he studies network protocol behaviour and IPv6 deployment. In the past, at Yahoo he ran the IPv6 program, and at Boundary he worked on traffic monitoring agents. He holds a PhD on network scalability from the University of Glasgow.",
    "title": "Monitoring what you don't own",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "718c7bd98260e95440736ec0ee43195c",
  },
  {
    "name": "Mandy Waite",
    "github": "tekgrrl",
    "twitter": "tekgrrl",
    "bio": "",
    "title": "Monitoring Serverless Things",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Quintessence Anx",
    "github": "quintessence",
    "twitter": "QuintessenceAnx",
    "bio": "",
    "title": "Unquantified Serendipity: Diversity in Development",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "8b9eab4b464b091b65578f026a4f8161",
  },
  {
    "name": "Alexis Lê-Quôc",
    "github": "alq666",
    "twitter": "alq",
    "bio": "",
    "title": "A thousand and one postmortems: lessons learned from running complex systems at scale",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "c3a42f6c504337f560cb69b9c37df659",
  },
  {
    "name": "Gregory Parker",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "Building a monitoring strategy and gaining consensus  Building a monitoring strategy and gaining consensus",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Trevor Morgan",
    "github": "",
    "twitter": "",
    "bio": "I've worked with monitoring in one way or another for most of my professional career within the financial services industry, starting off on Mainframe around 25 years ago, through to my current role in Standard Chartered Bank as Head of Monitoring Engineering. During this time, I've seen so much change and also seen things done well, badly and very badly.  But it is all good experience and helps to ensure the next iteration of a design or solution is that little bit better. I think I've enjoyed my roles so much because monitoring touches almost every technology, and we need to be a jack of all trades which as a technologist, keeps me on my toes.</br></br>More recently, I had a short spell on on a DevOps project in my previous role, where we had ambitious plans to change the way we did change.  That was a good learning point for me as it gave me the opportunity to think about how we can embed monitoring into the SDLC instead of what is nearly always an afterthought.</br></br>I'm more interested these days in how we can embed automation and self-service into our tooling and services, to place the control at our customers fingertips, as well as providing our data as a service so that they have the ability to build their own custom wrappers around the off-the-shelf offerings.",
    "title": "Building a monitoring strategy and gaining consensus",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "4a0b868a39e8239c450fe7f6ec34a844",
  },
  {
    "name": "Bram Vogelaar",
    "github": "attachmentgenie",
    "twitter": "",
    "bio": "Bram spent the first part of his career as a Molecular Biologist , he then moved on to supporting his peers by building tools and platforms for them with a lot of Open Source technologies, after which he joined Inuits to focus on helping more people to deliver their software with Open Source tools.",
    "title": "Gamification of Chaos Testing",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "ff1fa420f55d97bcd00c6cdf7faf9db7",
  },
  {
    "name": "Yan Cui",
    "github": "theburningmonk",
    "twitter": "theburningmonk",
    "bio": "Yan is an experienced engineer who has worked with AWS for near 10 years. He has been an architect and lead developer with a variety of industries ranging from investment banks, e-commerce to mobile gaming. In the last 2 years he has worked extensively with AWS Lambda in production, and he has been very active in sharing his experiences and the lessons he has learnt.</br></br>Yan is an <a href=\"https://aws.amazon.com/developer/community/heroes/yan-cui/\">AWS Serverless Hero</a>, and some of his work has even made their way into the Serverless Well-Architected whitepaper published by AWS. He is polyglot in both spoken and programming languages, is fluent in both English and Mandarin, and counts C#, F#, Scala, Node.js and Erlang amongst programming languages that he has worked with professionally.</br></br>Yan is a regular speaker at user groups and conferences internationally, and he is also the author of <a href=\"https://bit.ly/production-ready-serverless\">Production-Ready Serverless</a> and a co-author of <a href=\"https://bit.ly/fsharp-deep-dives\">F# Deep Dives</a>. In his spare time he keeps an active blog at <a href=\"https://theburningmonk.com/\">https://theburningmonk.com</a> where he shares his thoughts on topics such as AWS, serverless, functional programming and chaos engineering.",
    "title": "How to build observability into a serverless application",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "0bbaed5a18c131ba152cf566e1becaf8",
  },
  {
    "name": "Dominic Wellington",
    "github": "",
    "twitter": "dwellington",
    "bio": "Dominic Wellington is Director of Strategic Architecture for Europe at Moogsoft, helping companies adopt AIOps to streamline their IT Operations and become more agile and responsive to ever-changing demands. He has been involved in IT operations for a number of years, working in fields as diverse as SecOps, cloud computing, and data center automation.",
    "title": "How AI Helps Observe Decentralised Systems",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "4c2372bf1a00d68eff1c66dde75b107e",
  },
  {
    "name": "Rick Rackow",
    "github": "RiRa12621",
    "twitter": "rira12621",
    "bio": "Starting my professional career as a working student at the eBay Classifieds Group, I was part of a team tasked with build and release engineering as well as continuous integration pipelines for all of the eCG and in particular the teams based in Berlin. Later I joined the SiteOperations Engineering team as systems engineer, being  responsible for all German classifieds platforms. Since the beginning of 2018 I am facing a new challenge to run a completely new platform, containered and scalable with an on-premise OpenStack Cloud.",
    "title": "Nagios, Sensu, Prometheus - Why a change of the framework does not change the mindset",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "305c6c0e41d22e364762b4eb6a959cf7",
  },
  {
    "name": "Alexey Velikiy",
    "github": "jonyrock",
    "twitter": "jonyrock",
    "bio": "Alex is a hardcore software engineer. Worked in JetBrains, moved to R&D and then started his datavis journey focused on opensource monitoring software. Currently leads a small team that develops a self-hosted analysis tool for timeseries and provides development services to various clients including Grafana.",
    "title": "Self-hosted & open-source time series analysis for your infrastructure",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "185839e3593c3b1052df0a96497b2470",
  },
  {
    "name": "Joe Ross",
    "github": "",
    "twitter": "robusteza",
    "bio": "Joe is a data scientist at SignalFx, where he focuses on time series problems (anomaly detection, forecasting, correlation) that arise in monitoring. He holds a PhD in mathematics from Columbia University and was a researcher and instructor in pure mathematics, most recently at the University of Southern California. He has nine publications in peer-reviewed mathematics/statistics journals and has given talks about his research at conferences and universities throughout the world.",
    "title": "Incremental-decremental Methods For Real-Time Monitoring",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "2c45622ba5e0df7c693b15107d1ef3f5",
  },
]
