var rawSpeakers = [
  /* {
    "name": "",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  } */
  {
    "name": "Monica Sarbu",
    "github": "monicasarbu",
    "twitter": "monicasarbu",
    "bio": "Monica is leading the Ingest team at Elastic, responsible for the popular open source projects Beats (Filebeat, Metricbeat, Auditbeat, Winlogbeat, Packetbeat, Heartbeat) and Logstash, as well as the solutions built on top of the Beats platform like logging and monitoring and SecOps. She is the co-creator of Beats and the creator of the Packetbeat open source project. She gained extensive experience in the monitoring space by working for many years on a complete monitoring and troubleshooting solution for VoIP networks.",
    "title": "You don’t look like an Engineer",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "3be036b2f55557ceacebf476970662de",
  },
  {
    "name": "Marcus Barczak",
    "github": "ickymettle",
    "twitter": "ickymettle",
    "bio": "",
    "title": "Prometheus for Practitioners: Migrating to Prometheus at Fastly",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Michael Kehoe",
    "github": "michael-kehoe",
    "twitter": "matrixtek",
    "bio": "",
    "title": "What the NTSB teaches us about incident management & postmortems",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Nina Mushiana",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "What the NTSB teaches us about incident management & postmortems",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Stephen Boak",
    "github": "sboak",
    "twitter": "sboak",
    "bio": "",
    "title": "Rethinking UX for AI-driven Monitoring Tools",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "20be221be9bb28194db393512d90b2db",
  },
  {
    "name": "Radu Gheorghe",
    "github": "radu-gheorghe",
    "twitter": "radu0gheorghe",
    "bio": "Radu Gheorghe is a psychologist working as search consultant, software engineer and trainer at Sematext. Mainly on Elasticsearch, Solr and logging-related projects.",
    "title": "Is observability good for our brain? How about post-mortems?",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "2164d281261ff5f5a239a9ccd5bdcad4",
  },
  {
    "name": "Rafał Kuć",
    "github": "gr0",
    "twitter": "kucrafal",
    "bio": "",
    "title": "Is observability good for our brain? How about post-mortems?",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Stephen Strowes",
    "github": "sdstrowes",
    "twitter": "sdstrowes",
    "bio": "Stephen is a senior researcher in the R&D team at RIPE NCC; he studies network protocol behaviour and IPv6 deployment. In the past, at Yahoo he ran the IPv6 program, and at Boundary he worked on traffic monitoring agents. He holds a PhD on network scalability from the University of Glasgow.",
    "title": "Monitoring what you don't own",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "718c7bd98260e95440736ec0ee43195c",
  },
  {
    "name": "Mandy Waite",
    "github": "tekgrrl",
    "twitter": "tekgrrl",
    "bio": "",
    "title": "Monitoring Serverless Things",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Quintessence Anx",
    "github": "quintessence",
    "twitter": "QuintessenceAnx",
    "bio": "",
    "title": "Unquantified Serendipity: Diversity in Development",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Alexis Lê-Quôc",
    "github": "alq666",
    "twitter": "alq",
    "bio": "",
    "title": "A thousand and one postmortems: lessons learned from running complex systems at scale",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Gregory Parker",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "Building a monitoring strategy and gaining consensus  Building a monitoring strategy and gaining consensus",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Trevor Morgan",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "Building a monitoring strategy and gaining consensus",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Bram Vogelaar",
    "github": "attachmentgenie",
    "twitter": "",
    "bio": "",
    "title": "Gamification of Chaos Testing",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Yan Cui",
    "github": "theburningmonk",
    "twitter": "theburningmonk",
    "bio": "Yan is an experienced engineer who has worked with AWS for near 10 years. He has been an architect and lead developer with a variety of industries ranging from investment banks, e-commerce to mobile gaming. In the last 2 years he has worked extensively with AWS Lambda in production, and he has been very active in sharing his experiences and the lessons he has learnt.</br></br>Yan is an <a href=\"https://aws.amazon.com/developer/community/heroes/yan-cui/\">AWS Serverless Hero</a>, and some of his work has even made their way into the Serverless Well-Architected whitepaper published by AWS. He is polyglot in both spoken and programming languages, is fluent in both English and Mandarin, and counts C#, F#, Scala, Node.js and Erlang amongst programming languages that he has worked with professionally.</br></br>Yan is a regular speaker at user groups and conferences internationally, and he is also the author of <a href=\"https://bit.ly/production-ready-serverless\">Production-Ready Serverless</a> and a co-author of <a href=\"https://bit.ly/fsharp-deep-dives\">F# Deep Dives</a>. In his spare time he keeps an active blog at <a href=\"https://theburningmonk.com/\">https://theburningmonk.com</a> where he shares his thoughts on topics such as AWS, serverless, functional programming and chaos engineering.",
    "title": "How to build observability into a serverless application",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "0bbaed5a18c131ba152cf566e1becaf8",
  },
  {
    "name": "Dominic Wellington",
    "github": "",
    "twitter": "dwellington",
    "bio": "Dominic Wellington is Director of Strategic Architecture for Europe at Moogsoft, helping companies adopt AIOps to streamline their IT Operations and become more agile and responsive to ever-changing demands. He has been involved in IT operations for a number of years, working in fields as diverse as SecOps, cloud computing, and data center automation.",
    "title": "How AI Helps Observe Decentralised Systems",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "4c2372bf1a00d68eff1c66dde75b107e",
  },
  {
    "name": "Rick Rackow",
    "github": "RiRa12621",
    "twitter": "rira12621",
    "bio": "",
    "title": "Nagios, Sensu, Prometheus - Why a change of the framework does not change the mindset",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Alexey Velikiy",
    "github": "jonyrock",
    "twitter": "jonyrock",
    "bio": "",
    "title": "Self-hosted & open-source time series analysis for your infrastructure",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Joe Ross",
    "github": "",
    "twitter": "robusteza",
    "bio": "",
    "title": "Incremental-decremental Methods For Real-Time Monitoring",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
]
